spring:
  application:
    name: letter-loom

  datasource:
    url: jdbc:mysql://localhost:3306/letter-loom?createDatabaseIfNotExist=true
    username: root
    password: jiejie7jie

  jwt:
    secret: ${JWT_SECRET}