spring:
  application:
    name: letter-loom

  datasource:
    url: jdbc:mysql://localhost:3306/letter-loom?createDatabaseIfNotExist=true
    username: root
    password: jiejie7jie

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration : 900 # 15 mins
    refreshTokenExpiration: 604800 # 7 days

dictionary:
  apiUrl: ${DICTIONARY_API}